[routes]
; URL 

POST /login=Auth_Ctrl->login
POST /signup=Auth_Ctrl->registro
GET /menu/@id=Auth_Ctrl->getMenu
GET /tiposhabitaciones=Room_Ctrl->getTipos
GET /servicios=Room_Ctrl->getServicios
GET /pisos/@id=Room_Ctrl->getPisos
GET /numhabitaciones/@idtipo/@idpiso=Room_Ctrl->getNumerosHabitacion
GET /habitacionxid/@id=Room_Ctrl->getHabitacionById
POST /reservar=Reserve_Ctrl->nuevaReserva
POST /atender=Reserve_Ctrl->ocuparHabitacion
POST /cancelarreserva=Reserve_Ctrl->cancelarReservacion
POST /darmantenimiento=Room_Ctrl->ponerEnMantenimiento
POST /ponerdisponible=Room_Ctrl->estaDisponible
GET /estadohabitaciones=Reports_Ctrl->estadoDeHabitaciones
GET /habitacionesreservadas/@id=Reports_Ctrl->habitacionesXUser
GET /infohabitaciones/@id=Reports_Ctrl->infohabitaciones